name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: FExplorerRestarter.sln

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [x86, x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build for ${{ matrix.platform }}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild ${{env.SOLUTION_FILE_PATH}} /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{ matrix.platform }} -verbosity:diag
        
    - name: Find and Upload Build Artifacts
      run: |
        # Search for .exe files in the entire project folder
        for file in $(find . -name "*.exe"); do
          echo "Found executable: $file"
          echo "$file" >> files_to_upload.txt
        done
      shell: bash

    - name: Upload .exe Files
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.platform }}
        path: |
          $(cat files_to_upload.txt)
